### PR TITLE
Enable py39 on osx

### PR DESCRIPTION
**Pull request by marcelotduarte**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@isuruf Can you help me?
cx_Freeze 6.7 is build for conda, except for py39 osx.
This PR is a test only for this case. if I enable py39 (remove skip in meta), I get 20 errors:
```
2021-07-13T00:52:56.0057540Z   undef: _clock_settime
2021-07-13T00:52:56.0063370Z   undef: _fchownat
2021-07-13T00:52:56.0064430Z   undef: _readlinkat
2021-07-13T00:52:56.0065590Z   undef: _fchmodat
2021-07-13T00:52:56.0066070Z   undef: _futimens
2021-07-13T00:52:56.0066520Z   undef: _utimensat
2021-07-13T00:52:56.0066970Z   undef: _faccessat
2021-07-13T00:52:56.0068050Z   undef: _renameat
2021-07-13T00:52:56.0070050Z   undef: _fstatat$INODE64
2021-07-13T00:52:56.0070910Z   undef: _pwritev
2021-07-13T00:52:56.0071410Z   undef: _unlinkat
2021-07-13T00:52:56.0072070Z   undef: _mkdirat
2021-07-13T00:52:56.0072570Z   undef: _fdopendir$INODE64
2021-07-13T00:52:56.0073030Z   undef: _openat
2021-07-13T00:52:56.0073480Z   undef: _symlinkat
2021-07-13T00:52:56.0073920Z   undef: _getentropy
2021-07-13T00:52:56.0074340Z   undef: _linkat
2021-07-13T00:52:56.0074730Z   undef: _preadv
2021-07-13T00:52:56.0075100Z   undef: _clock_gettime
2021-07-13T00:52:56.0075560Z   undef: _clock_getres
2021-07-13T00:52:56.0076010Z   Undefined symbols for architecture x86_64:
2021-07-13T00:52:56.0076560Z     "_clock_settime", referenced from:
2021-07-13T00:52:56.0077070Z         _time_clock_settime in lto.o
2021-07-13T00:52:56.0077560Z         _time_clock_settime_ns in lto.o
2021-07-13T00:52:56.0078070Z     "_fchownat", referenced from:
2021-07-13T00:52:56.0078540Z         _os_chown_impl in lto.o
2021-07-13T00:52:56.0079060Z     "_readlinkat", referenced from:
2021-07-13T00:52:56.0079510Z         _os_readlink_impl in lto.o
2021-07-13T00:52:56.0080890Z     "_fchmodat", referenced from:
2021-07-13T00:52:56.0086620Z         _os_chmod_impl in lto.o
2021-07-13T00:52:56.0091030Z     "_futimens", referenced from:
2021-07-13T00:52:56.0097090Z         _utime_fd in lto.o
2021-07-13T00:52:56.0101470Z     "_utimensat", referenced from:
2021-07-13T00:52:56.0108240Z         _utime_nofollow_symlinks in lto.o
2021-07-13T00:52:56.0109130Z         _utime_dir_fd in lto.o
2021-07-13T00:52:56.0109710Z         _utime_default in lto.o
2021-07-13T00:52:56.0111830Z     "_faccessat", referenced from:
2021-07-13T00:52:56.0118210Z         _os_access_impl in lto.o
2021-07-13T00:52:56.0122590Z     "_renameat", referenced from:
2021-07-13T00:52:56.0128630Z         _internal_rename in lto.o
2021-07-13T00:52:56.0133080Z     "_fstatat$INODE64", referenced from:
2021-07-13T00:52:56.0139120Z         _DirEntry_fetch_stat in lto.o
2021-07-13T00:52:56.0140000Z         _posix_do_stat in lto.o
2021-07-13T00:52:56.0143640Z     "_pwritev", referenced from:
2021-07-13T00:52:56.0149650Z         _os_pwritev_impl in lto.o
2021-07-13T00:52:56.0154120Z     "_unlinkat", referenced from:
2021-07-13T00:52:56.0160480Z         _os_unlink_impl in lto.o
2021-07-13T00:52:56.0161140Z         _os_rmdir_impl in lto.o
2021-07-13T00:52:56.0164580Z     "_mkdirat", referenced from:
2021-07-13T00:52:56.0170380Z         _os_mkdir in lto.o
2021-07-13T00:52:56.0175060Z     "_fdopendir$INODE64", referenced from:
2021-07-13T00:52:56.0181110Z         _os_listdir in lto.o
2021-07-13T00:52:56.0182110Z         _os_scandir_impl in lto.o
2021-07-13T00:52:56.0185640Z     "_openat", referenced from:
2021-07-13T00:52:56.0192010Z         _os_open in lto.o
2021-07-13T00:52:56.0198170Z     "_symlinkat", referenced from:
2021-07-13T00:52:56.0204360Z         _os_symlink_impl in lto.o
2021-07-13T00:52:56.0209530Z     "_getentropy", referenced from:
2021-07-13T00:52:56.0266390Z         _py_getentropy in lto.o
2021-07-13T00:52:56.0278060Z     "_linkat", referenced from:
2021-07-13T00:52:56.0280420Z         _os_link_impl in lto.o
2021-07-13T00:52:56.0284460Z     "_preadv", referenced from:
2021-07-13T00:52:56.0285960Z         _os_preadv_impl in lto.o
2021-07-13T00:52:56.0287810Z     "_clock_gettime", referenced from:
2021-07-13T00:52:56.0293990Z         _pygettimeofday in lto.o
2021-07-13T00:52:56.0295550Z         _time_clock_gettime in lto.o
2021-07-13T00:52:56.0297020Z         _time_clock_gettime_ns in lto.o
2021-07-13T00:52:56.0298520Z         __PyTime_GetProcessTimeWithInfo in lto.o
2021-07-13T00:52:56.0300000Z         __PyTime_GetThreadTimeWithInfo in lto.o
2021-07-13T00:52:56.0301450Z     "_clock_getres", referenced from:
2021-07-13T00:52:56.0302810Z         _pygettimeofday in lto.o
2021-07-13T00:52:56.0304190Z         _time_clock_getres in lto.o
2021-07-13T00:52:56.0305700Z         __PyTime_GetProcessTimeWithInfo in lto.o
2021-07-13T00:52:56.0307230Z         __PyTime_GetThreadTimeWithInfo in lto.o
2021-07-13T00:52:56.0309220Z   ld: symbol(s) not found for architecture x86_64
2021-07-13T00:52:56.0516880Z   clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```
Using the reference: https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=macosx_sdk_version#requiring-newer-macos-sdks
Adding conda_build_config with MACOSX_SDK_VERSION 10.12 the errors are only (4) four.
With MACOSX_SDK_VERSION 10.13 the erros are 2. With MACOSX_SDK_VERSION 10.15 is the same.
The 2 errors:
```
2021-07-13T20:08:47.9806080Z     undef: _preadv
2021-07-13T20:08:47.9807760Z     undef: _pwritev
2021-07-13T20:08:47.9808380Z     Undefined symbols for architecture x86_64:
2021-07-13T20:08:47.9808940Z       "_preadv", referenced from:
2021-07-13T20:08:47.9809440Z           _os_preadv_impl in lto.o
2021-07-13T20:08:47.9814530Z       "_pwritev", referenced from:
2021-07-13T20:08:47.9821720Z           _os_pwritev_impl in lto.o
2021-07-13T20:08:47.9850710Z     ld: symbol(s) not found for architecture x86_64
2021-07-13T20:08:48.0053660Z     clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
2021-07-13T20:08:48.0070720Z     error: command '/Users/runner/miniforge3/conda-bld/cx_freeze_1626206528238/_build_env/bin/x86_64-apple-darwin13.4.0-clang' failed with exit code 1
```
The current patch has more changes but it does nothing more.
Note: I do not have mac to test, but I build cx_Freeze in Github Actions CI to run some test on macos-latest.

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Can you please keep my commit or add a `Co-authored-by:` tag? 

xref: https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by isuruf** [comment]
Thanks

**Comment by marcelotduarte** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotduarte** [comment]
> Can you please keep my commit or add a `Co-authored-by:` tag?

Yes, sure. When I updated the PR to enable all versions I forced the push. Excuse-me.
And thank you very much.

**Comment by marcelotduarte** [comment]
@jschueller Can you merge?
@isuruf Thank you very much for the help!

**Pull request merged**
